routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
*/

Route::get( '/', [ 'as' => 'home', 'uses' => 'PagesController@home' ] );
//Route::get( '/how_to_buy', [ 'as' => 'how_to_buy', 'uses' => 'PagesController@howToBuy' ] );
//Route::get( '/delivery', [ 'as' => 'delivery', 'uses' => 'PagesController@delivery' ] );
Route::get( '/load_price', [ 'as' => 'load_price', 'uses' => 'PagesController@load_price' ] );
Route::get( '/sales_price', [ 'as' => 'sales_price', 'uses' => 'PagesController@sales_price' ] );
Route::get( '/contacts', [ 'as' => 'contacts', 'uses' => 'PagesController@contacts' ] );
Route::get( '/about_us', [ 'as' => 'about_us', 'uses' => 'PagesController@about_us' ] );
Route::get( '/pay', [ 'as' => 'pay', 'uses' => 'PagesController@pay' ] );
Route::get( '/site_map', [ 'as' => 'site_map', 'uses' => 'PagesController@site_map' ] );

Route::get( '/store', [ 'as' => 'store', 'uses' => 'ProductsController@store' ] );
Route::get( '/store/category/{slug}', [ 'as' => 'category', 'uses' => 'ProductsController@store' ] );
Route::get( '/store/search', [ 'as' => 'search', 'uses' => 'SearchProductsController@searchIndex' ] );

Route::get( '/store/product/{slug}', [ 'as' => 'show_product', 'uses' => 'ProductsController@showProduct' ] );


Route::get( '/cart', [ 'as' => 'cart', 'uses' => 'CartController@showCard' ] );
Route::delete('/cart', [ 'as'=>'cart.delete', 'uses'=>'CartController@deleteCart']);

Route::post('/cart/add_item', [ 'as'=>'cart_item.add', 'uses'=>'CartController@setCartItemAmount']);
Route::post('/cart/sub_item', [ 'as'=>'cart_item.sub', 'uses'=>'CartController@setCartItemAmount']);
Route::delete('/cart/item', [ 'as'=>'cart_item.delete', 'uses'=>'CartController@deleteCartItem']);

Route::post( '/orders/create', [ 'as' => 'orders.create', 'uses' => 'OrdersController@createOrder' ] );
Route::get( '/orders/thanks', [ 'as' => 'orders.thanks', 'uses' => 'OrdersController@thanksOrder' ] );

Route::group( [ 'middleware' => [ 'auth' ] ], function () {
	Route::get( '/my_profile', [ 'as' => 'my_profile', 'uses' => 'PagesController@myProfile' ] );

    Route::get( '/after_registration', [ 'as' => 'after_registration', 'uses' => 'PagesController@after_registration' ] );
} );

Route::group( [ 'middleware' => [ 'auth' ], 'prefix' => 'orders', 'as' => 'orders.' ], function () {

	Route::get( '/', [ 'as' => 'list', 'uses' => 'OrdersController@listOrders' ] );
	Route::get( '/{id}', [ 'as' => 'show', 'uses' => 'OrdersController@showOrder' ] );
} );

Route::group( [ 'middleware' => [ 'auth', 'manager' ], 'prefix' => 'admin', 'as' => 'admin.' ], function () {
	Route::get( '/orders', [ 'as' => 'ordersList', 'uses' => 'AdminDashboardController@listOrders' ] );
	Route::get( '/orders/{id}', [ 'as' => 'ordersShow', 'uses' => 'AdminDashboardController@showOrder' ] );

    Route::get( '/orders/{id}/print', [ 'as' => 'print', 'uses' => 'OrdersController@print' ] )->where('id', '[0-9]+');

	Route::get( '/products', [ 'as' => 'addProducts', 'uses' => 'AdminDashboardController@addProducts' ] );

	Route::get( '/users', [ 'as' => 'users.index', 'uses' => 'AdminDashboardController@usersList' ] );
	Route::get( '/users/create', [ 'as' => 'users.create', 'uses' => 'UsersController@createUser' ] );
	Route::get( '/users/{id}/edit', [ 'as' => 'users.edit', 'uses' => 'UsersController@editUser' ] );

	Route::get( '/managers', [ 'as' => 'managers', 'uses' => 'AdminDashboardController@managersList' ] );

	Route::get( '/notes', [ 'as' => 'notes.index', 'uses' => 'NotesController@notesIndex' ] );
	Route::get( '/notes/create', [ 'as' => 'notes.create', 'uses' => 'NotesController@notesCreate' ] );
	Route::post( '/notes', [ 'as' => 'notes.store', 'uses' => 'NotesController@notesStore' ] );

	Route::get( '/send_email', [ 'as' => 'send_email', 'uses' => 'AdminDashboardController@sendEmail' ] );

	Route::post( '/products', [ 'as' => 'updateProducts', 'uses' => 'AddProductsController@updateProducts' ] );

    Route::get( '/sliders', [ 'as' => 'sliders.index', 'uses' => 'SlidersController@index' ] );
    Route::post( '/sliders', [ 'as' => 'sliders.store', 'uses' => 'SlidersController@store' ] );
    Route::get( '/sliders/create', [ 'as' => 'sliders.create', 'uses' => 'SlidersController@create' ] );
    Route::get( '/sliders/{id}/edit', [ 'as' => 'sliders.edit', 'uses' => 'SlidersController@edit' ] );
    Route::post( '/sliders/{id}', [ 'as' => 'sliders.edit', 'uses' => 'SlidersController@update' ] );

    Route::get( '/arrival', [ 'as' => 'arrival.index', 'uses' => 'ArrivalGoodsController@index' ] );
    Route::post( '/arrival', [ 'as' => 'arrival.store', 'uses' => 'ArrivalGoodsController@store' ] );
    Route::get( '/arrival/create', [ 'as' => 'arrival.create', 'uses' => 'ArrivalGoodsController@create' ] );
    Route::get( '/arrival/{id}/edit', [ 'as' => 'arrival.edit', 'uses' => 'ArrivalGoodsController@edit' ] );
    Route::post( '/arrival/{id}', [ 'as' => 'arrival.edit', 'uses' => 'ArrivalGoodsController@update' ] );

    Route::get( '/sales', [ 'as' => 'sales.index', 'uses' => 'SalesController@index' ] );
    Route::get( '/sales/create', [ 'as' => 'sales.create', 'uses' => 'SalesController@create' ] );
    Route::post( '/sales', [ 'as' => 'sales.store', 'uses' => 'SalesController@store' ] );
    Route::get( '/sales/{id}/edit', [ 'as' => 'sales.edit', 'uses' => 'SalesController@edit' ] )->where('id', '[0-9]+');
    Route::post( '/sales/{id}', [ 'as' => 'sales.edit', 'uses' => 'SalesController@update' ] )->where('id', '[0-9]+');
} );

Auth::routes();
Route::get('/logout', 'Auth\LoginController@logout');

Route::get('/get_updates', 'TelegramController@getUpdates');
Route::get('/postSendMessage', 'TelegramController@postSendMessage');

Route::get( '/get_file', [ 'as' => 'get_file', 'uses' => 'AdminDashboardController@getFile' ] );
Route::get( '/queue_method', [ 'as' => 'get_file', 'uses' => 'AdminDashboardController@queueMethod' ] );
Route::get( '/make_sitemap', [ 'as' => 'get_file', 'uses' => 'AdminDashboardController@sitemap' ] );

app/Models/Note.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Note extends Model
{
    protected $fillable = [
        'title','slug','content','product_id','type_news','type_shares','type_reviews','type_articles','thumbnail',
    ];

    public function addNewNote($data)
    {
        return Note::create([
            'title' => $data['title'],
            'slug' => str_slug($data['title'], '-'),
            'content' => $data['content'] ?? null,
            'product_id' => $data['product_id'] ?? null,
            'type_news' => $data['type_news'] ?? false,
            'type_shares' => $data['type_shares'] ?? false,
            'type_reviews' => $data['type_reviews'] ?? false,
            'type_articles' => $data['type_articles'] ?? true,
            'thumbnail' => $data['thumbnail'] ?? 'thumbnail',
        ]);
    }
}

app/Http/Controllers/NotesController.php
<?php

namespace App\Http\Controllers;

use App\Models\Note;
use Illuminate\Http\Request;

class NotesController extends Controller
{
    public function notesIndex(Request $request, Note $note){
        $data = $note->paginate(10);
        return view('notes.index',[
            'notes' => $data
        ]);
    }

    public function notesCreate(){
        return view('notes.create',[]);
    }

    public function notesStore(Request $request, Note $note){
        $note->addNewNote($request->all());
        $data = $note->paginate(10);
        return view('notes.index',[
            'notes' => $data
        ]);
    }
}

resources/views/notes/create.blade.php
@extends('layouts.index')

@section('content')
    <div class="container">
        <h1>Создать запись</h1>
    </div>
    <div class="container">
        <div class="row">
            <form class="col-xs-12 col-sm-12 col-md-12 col-lg-12" method="post" action="{{ route('admin.notes.store') }}">
                {{csrf_field()}}
                <div class="form-group">
                    <label for="inputTitle">Title</label>
                    <input type="text" class="form-control" id="inputTitle" placeholder="Title" name="title">
                </div>
                <div class="form-group">
                    <label for="inputThumbnail">Thumbnail</label>
                    <input type="file" id="inputThumbnail" placeholder="Thumbnail" name="thumbnail">
                    <p class="help-block">Select image for note's thumbnail</p>
                </div>
                <div class="form-group">
                    <label for="inputContent">Content</label>
                    <textarea class="form-control" id="inputContent" rows="3" placeholder="Content" name="content"></textarea>
                </div>
                <div class="checkbox">
                    <label>
                        <input type="checkbox" name="type_articles" checked value="1"> Article
                    </label>
                    <label>
                        <input type="checkbox" name="type_reviews" value="0"> Review
                    </label>
                    <label>
                        <input type="checkbox" name="type_shares" value="0"> Share
                    </label>
                    <label>
                        <input type="checkbox" name="type_news" value="0"> News
                    </label>
                </div>
                <button type="submit" class="btn btn-default">Submit</button>
            </form>
        </div>
    </div>
@stop

resources/views/notes/index.blade.php
@extends('layouts.index')

@section('content')
    <div class="container">
        <h1>Все записи</h1>
        <div class="addNoteSection">
            <a href="{{ route('admin.notes.create')  }}" class="btn btn-primary">Add new Note</a>
        </div>
    </div>
    <div class="container">
    @if( count($notes) > 0 )
        <table class="table table-bordered table-striped admin-table">
            <thead>
            <tr>
                <th>ID</th>
                <th>Title</th>
                <th>News</th>
                <th>Shares</th>
                <th>Reviews</th>
                <th>Articles</th>
            </tr>
            </thead>
            <tbody>
            @foreach($notes as $note)
                <tr>
                    <td>{{$note->id}}</td>
                    <td>{{$note->title}}</td>
                    <td>
                        <input type="checkbox" disabled
                                @if($note->type_news)
                                    checked
                                @endif>
                    </td>
                    <td>
                        <input type="checkbox" disabled
                               @if($note->type_shares)
                               checked
                                @endif>
                    </td>
                    <td>
                        <input type="checkbox" disabled
                               @if($note->type_reviews)
                               checked
                                @endif>
                    </td>
                    <td>
                        <input type="checkbox" disabled
                               @if($note->type_articles)
                               checked
                                @endif>
                    </td>
                </tr>
            @endforeach
            </tbody>
        </table>
    @else
        <div>
            Еще нет ни одной записи
        </div>
    @endif
    </div>
@stop