routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
*/

Route::get( '/', [ 'as' => 'home', 'uses' => 'PagesController@home' ] );
//Route::get( '/how_to_buy', [ 'as' => 'how_to_buy', 'uses' => 'PagesController@howToBuy' ] );
//Route::get( '/delivery', [ 'as' => 'delivery', 'uses' => 'PagesController@delivery' ] );
Route::get( '/load_price', [ 'as' => 'load_price', 'uses' => 'PagesController@load_price' ] );
Route::get( '/sales_price', [ 'as' => 'sales_price', 'uses' => 'PagesController@sales_price' ] );
Route::get( '/contacts', [ 'as' => 'contacts', 'uses' => 'PagesController@contacts' ] );
Route::get( '/about_us', [ 'as' => 'about_us', 'uses' => 'PagesController@about_us' ] );
Route::get( '/pay', [ 'as' => 'pay', 'uses' => 'PagesController@pay' ] );
Route::get( '/site_map', [ 'as' => 'site_map', 'uses' => 'PagesController@site_map' ] );

Route::get( '/store', [ 'as' => 'store', 'uses' => 'ProductsController@store' ] );
Route::get( '/store/category/{slug}', [ 'as' => 'category', 'uses' => 'ProductsController@store' ] );
Route::get( '/store/search', [ 'as' => 'search', 'uses' => 'SearchProductsController@searchIndex' ] );

Route::get( '/store/product/{slug}', [ 'as' => 'show_product', 'uses' => 'ProductsController@showProduct' ] );


Route::get( '/cart', [ 'as' => 'cart', 'uses' => 'CartController@showCard' ] );
Route::delete('/cart', [ 'as'=>'cart.delete', 'uses'=>'CartController@deleteCart']);

Route::post('/cart/add_item', [ 'as'=>'cart_item.add', 'uses'=>'CartController@setCartItemAmount']);
Route::post('/cart/sub_item', [ 'as'=>'cart_item.sub', 'uses'=>'CartController@setCartItemAmount']);
Route::delete('/cart/item', [ 'as'=>'cart_item.delete', 'uses'=>'CartController@deleteCartItem']);

Route::post( '/orders/create', [ 'as' => 'orders.create', 'uses' => 'OrdersController@createOrder' ] );
Route::get( '/orders/thanks', [ 'as' => 'orders.thanks', 'uses' => 'OrdersController@thanksOrder' ] );

Route::group( [ 'middleware' => [ 'auth' ] ], function () {
	Route::get( '/my_profile', [ 'as' => 'my_profile', 'uses' => 'PagesController@myProfile' ] );

    Route::get( '/after_registration', [ 'as' => 'after_registration', 'uses' => 'PagesController@after_registration' ] );
} );

Route::group( [ 'middleware' => [ 'auth' ], 'prefix' => 'orders', 'as' => 'orders.' ], function () {

	Route::get( '/', [ 'as' => 'list', 'uses' => 'OrdersController@listOrders' ] );
	Route::get( '/{id}', [ 'as' => 'show', 'uses' => 'OrdersController@showOrder' ] );
} );

Route::group( [ 'middleware' => [ 'auth', 'manager' ], 'prefix' => 'admin', 'as' => 'admin.' ], function () {
	Route::get( '/orders', [ 'as' => 'ordersList', 'uses' => 'AdminDashboardController@listOrders' ] );
	Route::get( '/orders/{id}', [ 'as' => 'ordersShow', 'uses' => 'AdminDashboardController@showOrder' ] );

    Route::get( '/orders/{id}/print', [ 'as' => 'print', 'uses' => 'OrdersController@print' ] )->where('id', '[0-9]+');

	Route::get( '/products', [ 'as' => 'addProducts', 'uses' => 'AdminDashboardController@addProducts' ] );

	Route::get( '/users', [ 'as' => 'users.index', 'uses' => 'AdminDashboardController@usersList' ] );
	Route::get( '/users/create', [ 'as' => 'users.create', 'uses' => 'UsersController@createUser' ] );
	Route::get( '/users/{id}/edit', [ 'as' => 'users.edit', 'uses' => 'UsersController@editUser' ] );

	Route::get( '/managers', [ 'as' => 'managers', 'uses' => 'AdminDashboardController@managersList' ] );

	Route::get( '/notes', [ 'as' => 'notes.index', 'uses' => 'NotesController@notesIndex' ] );
	Route::get( '/notes/create', [ 'as' => 'notes.create', 'uses' => 'NotesController@notesCreate' ] );
	Route::post( '/notes', [ 'as' => 'notes.store', 'uses' => 'NotesController@notesStore' ] );

	Route::get( '/send_email', [ 'as' => 'send_email', 'uses' => 'AdminDashboardController@sendEmail' ] );

	Route::post( '/products', [ 'as' => 'updateProducts', 'uses' => 'AddProductsController@updateProducts' ] );

    Route::get( '/sliders', [ 'as' => 'sliders.index', 'uses' => 'SlidersController@index' ] );
    Route::post( '/sliders', [ 'as' => 'sliders.store', 'uses' => 'SlidersController@store' ] );
    Route::get( '/sliders/create', [ 'as' => 'sliders.create', 'uses' => 'SlidersController@create' ] );
    Route::get( '/sliders/{id}/edit', [ 'as' => 'sliders.edit', 'uses' => 'SlidersController@edit' ] );
    Route::post( '/sliders/{id}', [ 'as' => 'sliders.edit', 'uses' => 'SlidersController@update' ] );

    Route::get( '/arrival', [ 'as' => 'arrival.index', 'uses' => 'ArrivalGoodsController@index' ] );
    Route::post( '/arrival', [ 'as' => 'arrival.store', 'uses' => 'ArrivalGoodsController@store' ] );
    Route::get( '/arrival/create', [ 'as' => 'arrival.create', 'uses' => 'ArrivalGoodsController@create' ] );
    Route::get( '/arrival/{id}/edit', [ 'as' => 'arrival.edit', 'uses' => 'ArrivalGoodsController@edit' ] );
    Route::post( '/arrival/{id}', [ 'as' => 'arrival.edit', 'uses' => 'ArrivalGoodsController@update' ] );

    Route::get( '/sales', [ 'as' => 'sales.index', 'uses' => 'SalesController@index' ] );
    Route::get( '/sales/create', [ 'as' => 'sales.create', 'uses' => 'SalesController@create' ] );
    Route::post( '/sales', [ 'as' => 'sales.store', 'uses' => 'SalesController@store' ] );
    Route::get( '/sales/{id}/edit', [ 'as' => 'sales.edit', 'uses' => 'SalesController@edit' ] )->where('id', '[0-9]+');
    Route::post( '/sales/{id}', [ 'as' => 'sales.edit', 'uses' => 'SalesController@update' ] )->where('id', '[0-9]+');
} );

Auth::routes();
Route::get('/logout', 'Auth\LoginController@logout');

Route::get('/get_updates', 'TelegramController@getUpdates');
Route::get('/postSendMessage', 'TelegramController@postSendMessage');

Route::get( '/get_file', [ 'as' => 'get_file', 'uses' => 'AdminDashboardController@getFile' ] );
Route::get( '/queue_method', [ 'as' => 'get_file', 'uses' => 'AdminDashboardController@queueMethod' ] );
Route::get( '/make_sitemap', [ 'as' => 'get_file', 'uses' => 'AdminDashboardController@sitemap' ] );

resources/views/admin/addProducts.blade.php
@extends('layouts.index')

@section('content')
<div class="container">
    <h1>Add products</h1>
</div>
<div class="container">
    <div class="row">

        <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
            <form id="updateProducts" class="" action="{{ route('admin.updateProducts')  }}" method="post">
                <div class="form-group">
                    <input id="updateProductsBtn" class="btn btn-primary" type="submit" value="Update products">
                </div>
            </form>
        </div>

    </div>
</div>
@stop

resources/views/admin/createArrivalGoods.blade.php
@extends('layouts.index')

@section('content')
    <div class="container usersList header_section">
        <h1 data-page="add_user">{{$pageName}}</h1>
        <a href="{{route('admin.arrival.index')}}" class="btn btn-success">Back</a>
    </div>
    <div class="container form_container">
        <div class="row">
            <div class="col-xs-12 col-sm-12 col-md-12  col-lg-12">

                <form action="{{ $action_url }}" id="addArrivalForm" method="post"
                      enctype="multipart/form-data">
                    {{ csrf_field() }}
                    @isset($arrival)
                        <input name="id" type="hidden" value="{{$arrival->id}}">
                    @endisset
                    <div class="form-group">
                        <label for="InputRoznica">Ссылка на розничный прайс</label>
                        <input name="price_user" type="text" class="form-control" id="InputRoznica" placeholder="Ссылка на розничный прайс"
                               value="{{ $arrival->price_user or '' }}">
                    </div>

                    <div class="form-group">
                        <label for="InputOprt3">Ссылка на опт #3 прайс</label>
                        <input name="price_3_opt" type="text" class="form-control" id="InputOprt3" placeholder="Ссылка на опт #3 прайс"
                               value="{{ $arrival->price_3_opt or '' }}">
                    </div>

                    <div class="form-group">
                        <label for="InputOprt8">Ссылка на опт #8 прайс</label>
                        <input name="price_8_opt" type="text" class="form-control" id="InputOprt8" placeholder="Ссылка на опт #8 прайс"
                               value="{{ $arrival->price_8_opt or '' }}">
                    </div>

                    <div class="form-group">
                        <label for="InputDealer">Ссылка на Диллер прайс</label>
                        <input name="price_dealer" type="text" class="form-control" id="InputDealer" placeholder="Ссылка на Диллер прайс"
                               value="{{ $arrival->price_dealer or '' }}">
                    </div>

                    <div class="form-group">
                        <label for="InputVip">Ссылка на VIP прайс</label>
                        <input name="price_vip" type="text" class="form-control" id="InputVip" placeholder="Ссылка на VIP прайс"
                               value="{{ $arrival->price_vip or '' }}">
                    </div>

                    <div class="form-group">
                        <label><input name="publish" type="checkbox" value="1"
                                      @if(isset($arrival) && $arrival->publish) checked @endif
                                      @if(!isset($arrival)) checked @endif
                            > Show arrival status</label>
                    </div>

                    <div class="form-group">
                        <label for="InputArrivalDate">Выберети дату прихода</label>
                        <input name="arrival_date" type="text" class="form-control" id="InputArrivalDate" placeholder="Выберети дату прихода"
                               value="{{ $arrival->arrival_date or '' }}">
                    </div>


                    <div class="form-group">
                        <button id="addSlider" class="btn btn-primary">
                            {{ (isset($arrival))?'Update':'Add' }} arrival
                        </button>
                    </div>
                </form>

            </div>
        </div>
    </div>
@stop

resources/views/admin/createSales.blade.php
@extends('layouts.index')

@section('content')
    <div class="container usersList header_section">
        <h1 data-page="add_user">{{$pageName}}</h1>
        <a href="{{route('admin.sales.index')}}" class="btn btn-success">Back</a>
    </div>
    <div class="container form_container">
        <div class="row">
            <div class="col-xs-12 col-sm-12 col-md-12  col-lg-12">

                @include('layouts.flash_messages')

                <form action="{{ $action_url }}" id="addArrivalForm" method="post"
                      enctype="multipart/form-data">
                    {{ csrf_field() }}
                    @isset($sale)
                        <input name="id" type="hidden" value="{{$sale->id}}">
                    @endisset
                    <div class="form-group">
                        <label for="InputRoznica">Ссылка на розничный прайс</label>
                        <input name="price_user" type="text" class="form-control" id="InputRoznica" placeholder="Ссылка на розничный прайс"
                               value="{{ $sale->price_user or '' }}" required>
                    </div>

                    <div class="form-group">
                        <label for="InputOprt3">Ссылка на опт #3 прайс</label>
                        <input name="price_3_opt" type="text" class="form-control" id="InputOprt3" placeholder="Ссылка на опт #3 прайс"
                               value="{{ $sale->price_3_opt or '' }}" required>
                    </div>

                    <div class="form-group">
                        <label for="InputOprt8">Ссылка на опт #8 прайс</label>
                        <input name="price_8_opt" type="text" class="form-control" id="InputOprt8" placeholder="Ссылка на опт #8 прайс"
                               value="{{ $sale->price_8_opt or '' }}" required>
                    </div>

                    <div class="form-group">
                        <label for="InputDealer">Ссылка на Диллер прайс</label>
                        <input name="price_dealer" type="text" class="form-control" id="InputDealer" placeholder="Ссылка на Диллер прайс"
                               value="{{ $sale->price_dealer or '' }}" required>
                    </div>

                    <div class="form-group">
                        <label for="InputVip">Ссылка на VIP прайс</label>
                        <input name="price_vip" type="text" class="form-control" id="InputVip" placeholder="Ссылка на VIP прайс"
                               value="{{ $sale->price_vip or '' }}" required>
                    </div>

                    <div class="form-group">
                        <label><input name="publish" type="checkbox" value="1"
                                      @if(isset($sale) && $sale->publish) checked @endif
                                      @if(!isset($sale)) checked @endif
                            > Show arrival status</label>
                    </div>

                    <div class="form-group">
                        <label for="InputArrivalDate">Выберети дату прихода</label>
                        <input name="sales_date" type="text" class="form-control" id="InputArrivalDate" placeholder="Выберети дату прихода"
                               value="{{ $sale->sales_date or '' }}" required>
                    </div>


                    <div class="form-group">
                        <button type="submit" id="addSlider" class="btn btn-primary">
                            {{ (isset($sale))?'Update':'Add' }} sale
                        </button>
                    </div>
                </form>

            </div>
        </div>
    </div>
@stop

resources/views/admin/listArrivalGoods.blade.php
@extends('layouts.index')

@section('content')
<div class="container header_section">
    <h1>{{$pageName}}</h1>
    <div class="addUserSection">
        <a href="{{route('admin.arrival.create')}}" class="btn btn-primary">Add new Arrival</a>
    </div>
</div>

<script>

    var app = new Vue({
        el: '#app',
        data: {
            arrivals: [
                @foreach($arrivals as $arrival)
                    { id: "{{$arrival->id}}", arrival_date: "{{$arrival->arrival_date}}" },
                @endforeach
            ]
        }
    })

</script>

<div class="container">
    <div class="row">
        <div class="col-xs-12 col-sm-12 col-md-12  col-lg-12">
            <div class="table-responsive">
                <table class="table table-bordered table-striped admin-table">
                    <thead>
                        <tr>
                            <th class="js-column-order" data-column="count">#</th>
                            <th class="js-column-order" data-column="id">ID</th>
                            <th class="js-column-order" data-column="arrival_date">Arrival date</th>
                            <th class="js-column-order" data-column="created_at">Created</th>
                            <th class="js-column-order">Action</th>
                        </tr>
                    </thead>
                    <tbody>
                        @forelse($arrivals as $arrival)
                            <tr>
                                <td data-count="{{$loop->iteration}}">{{$loop->iteration}}</td>
                                <td data-id="{{$arrival->id}}">{{ $arrival->id }}</td>
                                <td data-arrival_date="{{$arrival->arrival_date}}">{{ $arrival->arrival_date }}</td>
                                <td data-created_at="{{$arrival->created_at}}">{{ $arrival->created_at }}</td>

                                <td><a href="{{route('admin.arrival.index')}}/{{$arrival->id}}/edit">Edit</a></td>
                            </tr>
                        @empty

                        @endforelse
                    </tbody>
                </table>
            </div>
        </div>
        {{--<div id="pagination_link" class="col-sm-12 col-md-12 col-lg-12">{{$slidersList->links()}}</div>--}}
    </div>
</div>
@stop

resources/views/admin/listOrders.blade.php
@extends('layouts.index')

@section('content')
    <div class="container">
        <h1>Список заказов</h1>
    </div>

    <div class="container">
        <div class="row">
            <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
                <div class="table-responsive">
                    <table class="table table-bordered table-striped admin-table">
                        <thead>
                        <tr>
                            <th class="js-column-order" data-column="id">ID</th>
                            <th class="js-column-order" data-column="created_at">Дата</th>
                            <th class="js-column-order" data-column="mail">Почта</th>
                            <th class="js-column-order" data-column="name">ФИО</th>
                            <th class="js-column-order" data-column="phone">Телефон</th>
                            <th class="js-column-order" data-column="address">Адрес</th>
                            <th class="js-column-order" data-column="company">Компания</th>
                            <th class="js-column-order" data-column="manager">Менеджер</th>
                            <th class="js-column-order" data-column="price_type">Тип цены</th>
                            <th class="js-column-order" data-column="total">Всего</th>
                            <th class="js-column-order"></th>
                        </tr>
                        </thead>
                        <tbody>
                            @foreach($orderList as $item)
                            <tr>
                                <td data-id="{{$item->id}}">{{$item->id}}</td>
                                <td data-created_at="{{$item->created_at}}">{{$item->created_at}}</td>
                                <td data-mail="{{$item->email}}">{{$item->email ?? "Незарегистрированный"}}</td>
                                <td data-name="{{$item->fname}}">{{$item->fname}} {{$item->lname}}</td>
                                <td data-phone="{{$item->phone}}">{{$item->phone}}</td>
                                <td data-address="{{$item->address}}">{{$item->address}}</td>
                                <td data-company="{{$item->company}}">{{$item->company}}</td>
                                <td data-manager="{{$item->manager}}">{{$item->manager ?? "Неуказан"}}</td>
                                <td data-price_type="{{$item->price_type}}">{{$item->description ?? "Розничная"}}</td>
                                <td data-total="{{$item->total}}">{{$item->total}}</td>
                                <td>
                                    <div class="btn-group" role="group">
                                        <a class="btn btn-success" href="/admin/orders/{{$item->id}}">Детали</a>
                                        <a class="btn btn-danger" href="/admin/orders/{{$item->id}}/print">Отправить в 1С</a>
                                    </div>
                                </td>
                            </tr>
                            @endforeach
                        </tbody>
                    </table>
                </div>
            </div>
            <div id="pagination_link" class="col-sm-12 col-md-12 col-lg-12">{{$orderList->links()}}</div>
        </div>
    </div>
@stop

resources/views/admin/listSales.blade.php
@extends('layouts.index')

@section('content')
<div class="container header_section">
    <h1>{{$pageName}}</h1>
    <div class="addUserSection">
        <a href="{{route('admin.sales.create')}}" class="btn btn-primary">Add new Sale</a>
    </div>
</div>

<div class="container">
    <div class="row">
        <div class="col-xs-12 col-sm-12 col-md-12  col-lg-12">

            @include('layouts.flash_messages')

            <div class="table-responsive">
                <table class="table table-bordered table-striped admin-table">
                    <thead>
                        <tr>
                            <th class="js-column-order" data-column="count">#</th>
                            <th class="js-column-order" data-column="id">ID</th>
                            <th class="js-column-order" data-column="arrival_date">Sales date</th>
                            <th class="js-column-order" data-column="created_at">Created</th>
                            <th class="js-column-order">Action</th>
                        </tr>
                    </thead>
                    <tbody>
                        @forelse($sales as $sale)
                            <tr>
                                <td data-count="{{$loop->iteration}}">{{$loop->iteration}}</td>
                                <td data-id="{{$sale->id}}">{{ $sale->id }}</td>
                                <td data-sales_date="{{$sale->sales_date}}">{{ $sale->sales_date }}</td>
                                <td data-created_at="{{$sale->created_at}}">{{ $sale->created_at }}</td>

                                <td><a href="{{route('admin.sales.index')}}/{{$sale->id}}/edit">Edit</a></td>
                            </tr>
                        @empty

                        @endforelse
                    </tbody>
                </table>
            </div>
        </div>
        {{--<div id="pagination_link" class="col-sm-12 col-md-12 col-lg-12">{{$slidersList->links()}}</div>--}}
    </div>
</div>
@stop

resources/views/admin/listSliders.blade.php
@extends('layouts.index')

@section('content')
<div class="container header_section">
    <h1>{{$pageName}}</h1>
    <div class="addUserSection">
        <a href="{{route('admin.sliders.create')}}" class="btn btn-primary">Add new Slide</a>
    </div>
</div>
<div class="container">
    <div class="row">
        <div class="col-xs-12 col-sm-12 col-md-12  col-lg-12">
            <div class="table-responsive">
                <table class="table table-bordered table-striped admin-table">
                    <thead>
                    <tr>
                        <th class="js-column-order" data-column="count">#</th>
                        <th class="js-column-order" data-column="id">ID</th>
                        <th class="js-column-order" data-column="name">Slider name</th>
                        <th class="js-column-order" data-column="show_status">Show status</th>
                        <th class="js-column-order" data-column="text_title">Slider title</th>
                        <th class="js-column-order" data-column="created_at">Created</th>
                        <th class="js-column-order">Action</th>
                    </tr>
                    </thead>
                    <tbody>
                        @forelse($slidersList as $item)
                        <tr>
                            <td data-count="{{$loop->iteration}}">{{$loop->iteration}}</td>
                            <td data-id="{{$item->id}}">{{$item->id}}</td>
                            <td data-user="{{$item->name}}">{{$item->name}}</td>
                            <td><input type="checkbox" @if($item->show_status) checked @endif disabled></td>
                            <td data-status="{{$item->text_title}}">{{$item->text_title}}</td>
                            <td data-created_at="{{$item->created_at}}">{{$item->created_at}}</td>

                            <td><a href="{{route('admin.sliders.index')}}/{{$item->id}}/edit">Edit</a></td>
                        </tr>
                        @empty
                            <td colspan="7">No slides yet</td>
                        @endforelse
                    </tbody>
                </table>
            </div>
        </div>
        {{--<div id="pagination_link" class="col-sm-12 col-md-12 col-lg-12">{{$slidersList->links()}}</div>--}}
    </div>
</div>
@stop

resources/views/admin/sliderCreateNew.blade.php
@extends('layouts.index')

@section('content')
    <div class="container usersList header_section">
        <h1 data-page="add_user">{{$pageName}}</h1>
        <a href="{{route('admin.sliders.index')}}" class="btn btn-success">Back</a>
    </div>
    <div class="container form_container">
        <div class="row">
            <div class="col-xs-12 col-sm-12 col-md-12  col-lg-12">

                <form action="{{ $action_url }}" id="addUserForm" method="post"
                      enctype="multipart/form-data">
                    {{ csrf_field() }}
                    @isset($slider)
                        <input name="id" type="hidden" value="{{$slider->id}}">
                    @endisset
                    <div class="form-group">
                        <label for="InputName">Name</label>
                        <input name="name" type="text" class="form-control" id="InputName" placeholder="Enter name"
                               value="{{ $slider->name or '' }}">
                    </div>
                    <div class="form-group">
                        <label for="InputFile">Select image file</label>
                        <input name="img_url" type="file" id="InputFile" placeholder="Select image file">
                        @isset($slider)
                            <div class="preview_image">
                                <img src="/{{$slider->img_url}}" alt="">
                            </div>
                        @endisset
                    </div>
                    <div class="form-group">
                        <label><input name="show_status" type="checkbox" value="1"
                                      @if(isset($slider) && $slider->show_status) checked @endif> Show slider status</label>
                    </div>


                    <div class="form-group">
                        <label for="InputSliderTitle">Slider title text</label>
                        <input name="text_title" type="text" class="form-control" id="InputSliderTitle"
                               placeholder="Enter slider title text" value="{{ $slider->text_title or '' }}">
                    </div>
                    <div class="form-group">
                        <label for="InputSliderContent">Slider title text</label>
                        <textarea name="text_content" id="InputSliderContent" class="form-control" rows="3"
                                  placeholder="Enter slider content text">{{ $slider->text_content or '' }}</textarea>
                    </div>
                    <div class="form-group">
                        <label for="InputSliderButton">Slider button text</label>
                        <input name="text_button" type="text" class="form-control" id="InputSliderButton"
                               placeholder="Enter slider button text" value="{{ $slider->text_button or '' }}">
                    </div>

                    <div class="form-group">
                        <label for="InputButtonURL">Button link URL</label>
                        <input name="link_url" type="text" class="form-control" id="InputButtonURL"
                               placeholder="Enter button link URL" value="{{ $slider->link_url or '' }}">
                    </div>
                    <div class="form-group">
                        <label><input name="light_theme" type="checkbox" value="1" @if(isset($slider) && $slider->light_theme) checked @endif> Select light theme</label>
                    </div>

                    <div class="form-group">
                        <button id="addSlider" class="btn btn-primary">
                            {{ (isset($slider))?'Update':'Add' }} slide
                        </button>
                    </div>
                </form>

            </div>
        </div>
    </div>
@stop

resources/views/admin/usersList.blade.php
@extends('layouts.index')

@section('content')
<div class="container usersList header_section">
    <h1>Список пользователей</h1>
    <div class="addUserSection">
        <a href="{{ route('admin.users.create')  }}" class="btn btn-primary">Добавить нового</a>
    </div>
</div>
<div class="container">
    <div class="row">
        <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
            <div class="table-responsive">
                <table class="table table-bordered table-striped admin-table">
                    <thead>
                        <tr>
                            <th class="js-column-order" data-column="id">id</th>
                            <th class="js-column-order" data-column="created_at">Дата регистрации</th>
                            <th class="js-column-order" data-column="flname">ФИО</th>
                            <th class="js-column-order" data-column="phone">Телефон</th>
                            <th class="js-column-order" data-column="email">Email</th>
                            <th class="js-column-order" data-column="address">Адрес</th>
                            <th class="js-column-order" data-column="company">Компания</th>
                            <th class="js-column-order" data-column="price_type">Тип цены</th>
                            <th class="js-column-order" data-column="manager_id">Менеджер</th>
                            <th></th>
                        </tr>
                    </thead>
                    <tbody>
                    @foreach($users as $user)
                        {{-- Hide admins --}}
                        @if( ($user->role == 'admin' || $user->role == 'manager') && Auth::user()->role != 'admin' )
                            @continue
                        @endif

                        <tr class="js-row user-item" data-id="{{$user->id}}">
                            <td class="js-id" data-row="{{$user->id}}">{{$user->id}}</td>
                            <td class="js-created_at" data-row="{{$user->created_at}}">{{$user->created_at}}</td>
                            <td class="js-flname" data-row="{{$user->fname}} {{$user->lname}}">
                                {{$user->fname}}
                                {{$user->lname}}
                                (
                                @if($user->status == 1)
                                    <span style="color: green">Проверенный</span>
                                @else
                                    <span style="color: red">Новый</span>
                                @endif
                                )
                            </td>
                            <td class="js-phone" data-row="{{$user->phone}}">{{$user->phone}}</td>
                            <td class="js-email" data-row="{{$user->email}}">{{$user->email}}</td>
                            <td class="js-address" data-row="{{$user->address}}">{{$user->address}}</td>
                            <td class="js-company" data-row="{{$user->company}}">{{$user->company}}</td>
                            <td class="js-price_type" data-row="{{$user->price_type}}">{{$priceTypeList[$user->price_type-1]['description']}}</td>
                            <td class="js-manager_id" data-row="{{$user->manager->id}}">{{$user->manager->name}}</td>
                            <td><a class="btn btn-success" href="{{route('admin.users.index')}}/{{$user->id}}/edit">Редактировать</a></td>
                        </tr>
                    @endforeach
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>
@stop